#import <Cocoa/Cocoa.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "clipboard_darwin.h"

// Markers by which a source app asks clipboard managers to skip a payload.
// See http://nspasteboard.org
static NSString *const kConcealedType = @"org.nspasteboard.ConcealedType";
static NSString *const kTransientType = @"org.nspasteboard.TransientType";
static NSString *const kAutoGenerated = @"org.nspasteboard.AutoGeneratedType";

// Universal Clipboard marks a pasteboard filled from another device (Handoff)
// with this type. It is undocumented but stable, and it is the only signal the
// pasteboard carries about the copy's origin -- it names no device, and there
// is no local app to attribute the copy to. When it disappears from a future
// macOS the copy is simply recorded as a local one, as before.
static NSString *const kRemoteClipboard = @"com.apple.is-remote-clipboard";

static pid_t gRememberedPID = 0;

static char *copyCString(NSString *s) {
    if (s == nil) {
        return NULL;
    }
    const char *utf8 = [s UTF8String];
    if (utf8 == NULL) {
        return NULL;
    }
    return strdup(utf8);
}

long long gedaChangeCount(void) {
    @autoreleasepool {
        return (long long)[[NSPasteboard generalPasteboard] changeCount];
    }
}

// AppKit can rasterise more than PNG and TIFF (for example JPEG, HEIC, PDF and
// SVG). Source apps are not required to publish AppKit's converted TIFF flavor,
// so match every representation NSImage can actually decode.
static NSSet<NSPasteboardType> *readableImageTypes(void) {
    static NSSet<NSPasteboardType> *types;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        // Process-lifetime cache. This file is compiled without ARC.
        types = [[NSSet alloc] initWithArray:[NSImage imageTypes]];
    });
    return types;
}

// Converts one declared image representation into the PNG contract used by Go.
// dataAvailable distinguishes a lazy provider from malformed image data: only
// the former is worth retrying on the next watcher tick.
static NSData *pngFromPasteboard(NSPasteboard *pb, NSPasteboardType type,
                                 BOOL *dataAvailable) {
    NSData *data = [pb dataForType:type];
    *dataAvailable = data != nil && [data length] > 0;
    if (!*dataAvailable) {
        return nil;
    }
    if ([type isEqualToString:NSPasteboardTypePNG]) {
        return data;
    }

    NSBitmapImageRep *rep = [NSBitmapImageRep imageRepWithData:data];
    if (rep != nil) {
        return [rep representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
    }

    // Vector representations such as PDF and SVG need NSImage to rasterise
    // them before NSBitmapImageRep can encode the pixels as PNG.
    NSImage *image = [[NSImage alloc] initWithData:data];
    if (image == nil) {
        return nil;
    }
    NSRect rect = NSMakeRect(0, 0, [image size].width, [image size].height);
    CGImageRef cgImage = [image CGImageForProposedRect:&rect context:nil hints:nil];
    if (cgImage == nil) {
        [image release];
        return nil;
    }
    NSBitmapImageRep *bitmap = [[NSBitmapImageRep alloc] initWithCGImage:cgImage];
    NSData *png = [bitmap representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
    [bitmap release];
    [image release];
    return png;
}

void gedaRead(int *kind, char **text, void **img, int *imgLen,
              int *concealed, int *transient, int *remote, int *pending) {
    @autoreleasepool {
        *kind = 0;
        *text = NULL;
        *img = NULL;
        *imgLen = 0;
        *concealed = 0;
        *transient = 0;
        *remote = 0;
        *pending = 0;

        NSPasteboard *pb = [NSPasteboard generalPasteboard];
        NSArray<NSPasteboardType> *types = [pb types];
        if (types == nil || [types count] == 0) {
            // Chrome can advance the pasteboard counter before pboard has
            // published the new item's types. Treat that brief empty state as
            // pending, or the watcher consumes the counter and never sees the
            // image that appears behind the same change a moment later.
            *pending = 1;
            return;
        }

        if ([types containsObject:kRemoteClipboard]) {
            *remote = 1;
        }
        if ([types containsObject:kConcealedType]) {
            *concealed = 1;
        }
        if ([types containsObject:kTransientType] || [types containsObject:kAutoGenerated]) {
            *transient = 1;
        }

        // Walk the types in the order the source app declared them and take the
        // first one we understand, so we honour its notion of the primary
        // representation.
        for (NSPasteboardType type in types) {
            BOOL isText = [type isEqualToString:NSPasteboardTypeString] ||
                          [type isEqualToString:@"public.utf8-plain-text"] ||
                          [type isEqualToString:NSPasteboardTypeRTF] ||
                          [type isEqualToString:NSPasteboardTypeHTML] ||
                          [type isEqualToString:NSPasteboardTypeURL] ||
                          [type isEqualToString:@"public.file-url"];
            BOOL isImage = [readableImageTypes() containsObject:type];

            if (isText) {
                // A previously declared image is the source app's preferred
                // representation. Do not consume its lower-priority text
                // fallback while the lazy image provider is still rendering.
                if (*pending) {
                    continue;
                }
                NSString *s = [pb stringForType:NSPasteboardTypeString];
                if (s != nil && [s length] > 0) {
                    *kind = 1;
                    *text = copyCString(s);
                    return;
                }
                // Declared text but nothing readable as a plain string; keep
                // looking for an image representation.
                continue;
            }

            if (isImage) {
                BOOL dataAvailable = NO;
                NSData *png = pngFromPasteboard(pb, type, &dataAvailable);
                if (png != nil && [png length] > 0) {
                    void *buf = malloc([png length]);
                    if (buf != NULL) {
                        memcpy(buf, [png bytes], [png length]);
                        *kind = 2;
                        *img = buf;
                        *imgLen = (int)[png length];
                        *pending = 0;
                    }
                    return;
                }
                if (!dataAvailable) {
                    *pending = 1;
                }
                continue;
            }
        }

        // Nothing matched by type name; fall back to a plain string only when
        // no higher-priority image representation is still pending.
        if (!*pending) {
            NSString *s = [pb stringForType:NSPasteboardTypeString];
            if (s != nil && [s length] > 0) {
                *kind = 1;
                *text = copyCString(s);
            }
        }
    }
}

long long gedaWriteText(const char *text) {
    @autoreleasepool {
        if (text == NULL) {
            return 0;
        }
        NSString *s = [NSString stringWithUTF8String:text];
        if (s == nil) {
            return 0;
        }
        NSPasteboard *pb = [NSPasteboard generalPasteboard];
        [pb clearContents];
        [pb setString:s forType:NSPasteboardTypeString];
        return (long long)[pb changeCount];
    }
}

long long gedaWriteImage(const void *bytes, int len) {
    @autoreleasepool {
        if (bytes == NULL || len <= 0) {
            return 0;
        }
        NSData *data = [NSData dataWithBytes:bytes length:len];
        NSPasteboard *pb = [NSPasteboard generalPasteboard];
        [pb clearContents];
        [pb setData:data forType:NSPasteboardTypePNG];

        // Also offer TIFF: some older apps only accept that.
        NSBitmapImageRep *rep = [NSBitmapImageRep imageRepWithData:data];
        if (rep != nil) {
            NSData *tiff = [rep TIFFRepresentation];
            if (tiff != nil) {
                [pb setData:tiff forType:NSPasteboardTypeTIFF];
            }
        }
        return (long long)[pb changeCount];
    }
}

void gedaFrontmost(char **name, char **bundleID) {
    @autoreleasepool {
        *name = NULL;
        *bundleID = NULL;

        NSRunningApplication *app = [[NSWorkspace sharedWorkspace] frontmostApplication];
        if (app == nil) {
            return;
        }
        *name = copyCString([app localizedName]);
        *bundleID = copyCString([app bundleIdentifier]);
    }
}

void *gedaAppIconPNG(const char *bundleID, int px, int *outLen) {
    @autoreleasepool {
        *outLen = 0;
        if (bundleID == NULL || px <= 0) {
            return NULL;
        }
        NSString *bid = [NSString stringWithUTF8String:bundleID];
        if (bid == nil) {
            return NULL;
        }

        NSWorkspace *ws = [NSWorkspace sharedWorkspace];
        NSString *path = [ws absolutePathForAppBundleWithIdentifier:bid];
        if (path == nil) {
            return NULL;
        }
        NSImage *icon = [ws iconForFile:path];
        if (icon == nil) {
            return NULL;
        }

        // Render at the requested size so the encoded PNG stays small.
        NSSize target = NSMakeSize(px, px);
        NSBitmapImageRep *rep = [[NSBitmapImageRep alloc]
            initWithBitmapDataPlanes:NULL
                          pixelsWide:px
                          pixelsHigh:px
                       bitsPerSample:8
                     samplesPerPixel:4
                            hasAlpha:YES
                            isPlanar:NO
                      colorSpaceName:NSCalibratedRGBColorSpace
                         bytesPerRow:0
                        bitsPerPixel:0];
        if (rep == nil) {
            return NULL;
        }

        NSGraphicsContext *ctx = [NSGraphicsContext graphicsContextWithBitmapImageRep:rep];
        [NSGraphicsContext saveGraphicsState];
        [NSGraphicsContext setCurrentContext:ctx];
        [icon drawInRect:NSMakeRect(0, 0, target.width, target.height)
                fromRect:NSZeroRect
               operation:NSCompositingOperationSourceOver
                fraction:1.0];
        [NSGraphicsContext restoreGraphicsState];

        NSData *png = [rep representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
        [rep release];

        if (png == nil || [png length] == 0) {
            return NULL;
        }
        void *buf = malloc([png length]);
        if (buf == NULL) {
            return NULL;
        }
        memcpy(buf, [png bytes], [png length]);
        *outLen = (int)[png length];
        return buf;
    }
}

void gedaRememberFrontmost(void) {
    @autoreleasepool {
        NSRunningApplication *app = [[NSWorkspace sharedWorkspace] frontmostApplication];
        if (app == nil) {
            return;
        }
        // Ignore ourselves: if our popup is already frontmost, keep whatever we
        // remembered previously so paste still reaches the user's app.
        if ([app processIdentifier] == [[NSRunningApplication currentApplication] processIdentifier]) {
            return;
        }
        gRememberedPID = [app processIdentifier];
    }
}

// gedaActivateRemembered brings the application captured by
// gedaRememberFrontmost back to the front and waits until it is actually
// active. Returns 1 when the target holds focus.
//
// Activation is not an Accessibility facility: NSRunningApplication grants it
// to any app, sandboxed or not, and it needs no permission. That is what makes
// it the whole of the paste path in the App Store build, where the entry is
// copied and the user presses the paste shortcut themselves. Without it the
// keystroke would land nowhere, because hiding our panel leaves this process
// active with no window to receive it.
int gedaActivateRemembered(void) {
    @autoreleasepool {
        if (gRememberedPID == 0) {
            return 0;
        }
        NSRunningApplication *target =
            [NSRunningApplication runningApplicationWithProcessIdentifier:gRememberedPID];
        if (target == nil) {
            return 0;
        }
        if ([target isActive]) {
            return 1;
        }

        [target activateWithOptions:NSApplicationActivateIgnoringOtherApps];

        // Activation is asynchronous. A caller that types into the target
        // immediately would reach the wrong app, so wait for it to take focus.
        for (int i = 0; i < 40 && ![target isActive]; i++) {
            usleep(10 * 1000);
        }
        return [target isActive] ? 1 : 0;
    }
}
