// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearAll() {
  return window['go']['main']['App']['ClearAll']();
}

export function ClearHistoryAndStatistics() {
  return window['go']['main']['App']['ClearHistoryAndStatistics']();
}

export function CopyOnly(arg1) {
  return window['go']['main']['App']['CopyOnly'](arg1);
}

export function Count() {
  return window['go']['main']['App']['Count']();
}

export function DefaultSettings() {
  return window['go']['main']['App']['DefaultSettings']();
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function Env() {
  return window['go']['main']['App']['Env']();
}

export function FullImage(arg1) {
  return window['go']['main']['App']['FullImage'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatistics(arg1) {
  return window['go']['main']['App']['GetStatistics'](arg1);
}

export function HidePopup() {
  return window['go']['main']['App']['HidePopup']();
}

export function List(arg1) {
  return window['go']['main']['App']['List'](arg1);
}

export function ListPinned() {
  return window['go']['main']['App']['ListPinned']();
}

export function NotificationStatus() {
  return window['go']['main']['App']['NotificationStatus']();
}

export function OnLeftClick(arg1) {
  return window['go']['main']['App']['OnLeftClick'](arg1);
}

export function OnRightClick(arg1) {
  return window['go']['main']['App']['OnRightClick'](arg1);
}

export function OnWindowBlur() {
  return window['go']['main']['App']['OnWindowBlur']();
}

export function OpenPastePermissionSettings() {
  return window['go']['main']['App']['OpenPastePermissionSettings']();
}

export function PasteItem(arg1) {
  return window['go']['main']['App']['PasteItem'](arg1);
}

export function PastePermission() {
  return window['go']['main']['App']['PastePermission']();
}

export function PasteSupported() {
  return window['go']['main']['App']['PasteSupported']();
}

export function PopupGutter() {
  return window['go']['main']['App']['PopupGutter']();
}

export function PopupHeight() {
  return window['go']['main']['App']['PopupHeight']();
}

export function PopupWidth() {
  return window['go']['main']['App']['PopupWidth']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RequestNotificationPermission() {
  return window['go']['main']['App']['RequestNotificationPermission']();
}

export function RequestPastePermission() {
  return window['go']['main']['App']['RequestPastePermission']();
}

export function ResetStatistics() {
  return window['go']['main']['App']['ResetStatistics']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Select(arg1) {
  return window['go']['main']['App']['Select'](arg1);
}

export function SendTestNotification() {
  return window['go']['main']['App']['SendTestNotification']();
}

export function SetPinnedPriority(arg1) {
  return window['go']['main']['App']['SetPinnedPriority'](arg1);
}

export function ShowSettings() {
  return window['go']['main']['App']['ShowSettings']();
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function TogglePopup() {
  return window['go']['main']['App']['TogglePopup']();
}

export function UpdatesSupported() {
  return window['go']['main']['App']['UpdatesSupported']();
}
