// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {main} from '../models';
import {store} from '../models';
import {tray} from '../models';

export function CheckForUpdates():Promise<void>;

export function ClearAll():Promise<void>;

export function CopyOnly(arg1:string):Promise<void>;

export function Count():Promise<number>;

export function DefaultSettings():Promise<settings.Settings>;

export function Delete(arg1:string):Promise<void>;

export function Env():Promise<main.Environment>;

export function FullImage(arg1:string):Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function HidePopup():Promise<void>;

export function List(arg1:string):Promise<Array<store.Item>>;

export function NotificationStatus():Promise<string>;

export function OnLeftClick(arg1:tray.Anchor):Promise<void>;

export function OnRightClick(arg1:tray.Anchor):Promise<void>;

export function OnWindowBlur():Promise<void>;

export function PasteItem(arg1:string):Promise<void>;

export function PopupGutter():Promise<number>;

export function PopupHeight():Promise<number>;

export function PopupWidth():Promise<number>;

export function Quit():Promise<void>;

export function RequestNotificationPermission():Promise<string>;

export function RequestPastePermission():Promise<boolean>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function Select(arg1:string):Promise<void>;

export function SendTestNotification():Promise<void>;

export function ShowSettings():Promise<void>;

export function TogglePin(arg1:string):Promise<boolean>;

export function TogglePopup():Promise<void>;

export function UpdatesSupported():Promise<boolean>;
